### PR TITLE
Modules only need to be loaded once

### PR DESCRIPTION
**Pull request by coffeemedia**
Raises issues on unit tests

### CODE REVIEW

**Comment by rspieker** [comment]
The need for this change implies the surrounding logic which 'manually' checks whether or not the file is already included fails.

Can you provide the steps to reproduce, or at least the exact error message PHP gives? 
I don't seem to get this error on the latest unittest branch

**Comment by coffeemedia** [comment]
The error message states 
`PHPUnit_Framework_Exception: PHP Fatal error:  Cannot redeclare class CoreDBMySQLException in /var/www/konsolidate/core/db/mysql/exception.class.php on line 60`

Issue pops up for the first time with the (or this) implementation of the phpunit tests. Nevertheless, the manual check might be overkill with an include_once statement.

To perform the test you need to run the `make composer-update` command and prepare a local MySQL database. The configuration that is used is stored in test/phpunit.xml. The required table create syntax can be found below.

`CREATE TABLE `languageswitchphrase` (
  `lspid` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `lspphrase` varchar(255) DEFAULT NULL,
  `lspmodifiedts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lspcreatedts` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`lspid`),
  UNIQUE KEY `lspphrase` (`lspphrase`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `languageswitchtranslation` (
  `lstid` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `lspid` int(11) unsigned DEFAULT NULL,
  `lsttranslation` varchar(255) DEFAULT NULL,
  `lstlocale` varchar(10) DEFAULT 'nl_nl',
  `lstenabled` tinyint(1) DEFAULT '1',
  `lstmodifiedts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lstcreatedts` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`lstid`),
  UNIQUE KEY `lspid_locale` (`lspid`,`lstlocale`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;`

**Comment by rspieker** [comment]
Went in for a quick look at what is the root-cause for this unexpected behaviour (will address the benefits of `include_once` after the cause).

The problem is that the `import` method expects the path to be inside the modules path, which in general is true, except for `DB/MySQL/Query` which also imports the exception class, by using:
`$this->import('../exception.class.php')`
instead of
`$this->call('../import', 'exception.class.php');
Which would make the inclusion relative to the `DB/MySQL` model. To be fair, this should have been taken care of by the first lines of the import method.

While I do agree `include_once` does reduce the the complexity of the import function, the solution as implemented was - at some point in time - faster than `include_once`. As it would "know" when to actually include files (considering it does in fact traverse all possible candidate files across all tiers).
I'm not sure whether that argument still holds, as this particular piece of code was implemented 9 years ago (_wow_, August 2nd 2007), at lot has changed since.

In order to fix the root cause without deviating from the original considerations, I suggest the following change instead:

```
$sCurrentFile = realpath("{$sPath}/" . strToLower( $sFile ));
if ( isset( $aIncluded[ $sCurrentFile ] ) )
{
	$bImported = true;
}
else if ( $sCurrentFile )
{
	include( $sCurrentFile );
	$bImported = true;
}
```
This simply moves the `realpath` check up, so the real path is actually checked against the included files. It may turn out to be actually slower than `include_once`.

If we are going to implement the `include_once`, as it does have the benefit is less complexity, I'd favour a variant where the entire function would be simplified, e.g.

From:
```
$aIncluded = array_flip( get_included_files() );
$aPath     = array_reverse( $this->_path, true );
$bImported = false;
foreach ( $aPath as $sPath )
{
	$sCurrentFile = "{$sPath}/" . strToLower( $sFile );
	if ( isset( $aIncluded[ $sCurrentFile ] ) )
	{
		$bImported = true;
	}
	else if ( realpath( $sCurrentFile ) )
	{
		include_once( $sCurrentFile );
		$bImported = true;
	}
}
```

To:
```
$aPath     = array_reverse( $this->_path, true );
$bImported = false;
foreach ( $aPath as $sPath )
{
	$sCurrentFile = realpath( "{$sPath}/" . strToLower( $sFile ) );
	if ($sCurrentFile )
	{
		include_once( $sCurrentFile );
		$bImported = true;
	}
}
```

I honestly don't know which approach I prefer as I'm not sure which is the fastest.

**Comment by rspieker** [comment]
Thank you very much!

**Pull request merged**
